### ISSUE TITLE
bug when zooming into a large inversion at the very beginning of a chromosome

### ISSUE THREAD

**Issue by StefanoLonardi** [schneebergerlab/plotsr#7]
Thanks for your great tool. I have been using it to generate the plot below comparing seven accession of our plant genome
[plotsr_all_genomes.pdf](https://github.com/schneebergerlab/plotsr/files/8021328/plotsr_all_genomes.pdf)

I have been able to generate zoom-in for all chromosomes, but when I try to zoom into chromosome 6, which has a large 8Mbp inversion right at the beginning of the chromosome I get an incomplete picture. I am using `--reg IT97K:chr06:1-12000000` to select that region.
[chr06a.pdf](https://github.com/schneebergerlab/plotsr/files/8021384/chr06a.pdf)

If instead I use `--reg IT97K:chr06:1-9000000` I get an error message
```
Traceback (most recent call last):
  File "/home/stelo/miniconda3/envs/py38/bin/plotsr", line 6, in <module>
    main(sys.argv[1:])
  File "/home/stelo/miniconda3/envs/py38/lib/python3.8/site-packages/plotsr/main.py", line 44, in main
    plotsr(args)
  File "/home/stelo/miniconda3/envs/py38/lib/python3.8/site-packages/plotsr/plotsr.py", line 175, in plotsr
    alignments, chrs, chrgrps = selectregion(REG, chrlengths, alignments, chrids)
  File "/home/stelo/miniconda3/envs/py38/lib/python3.8/site-packages/plotsr/func.py", line 903, in selectregion
    if min(syncrd['astart']) < s:
ValueError: min() arg is an empty sequence
```

**Comment by mnshgl0110** [comment]
The `--reg` parameter uses synteny between genomes to find homologous regions. Earlier, SRs that are outside the syntenic homologous regions were not plotted leading to the 'incomplete' image. I added the `--rtr` parameter yesterday using which it should be possible to get the inversion plotted. Please try with the updated version.

I think that `IT97K:chr06:1-9000000` is leading to selection of regions that do not have any synteny which is resulting in this error. Zooming out to include syntenic regions should resolve this issue.

**Comment by StefanoLonardi** [comment]
Hi Manish, thanks for the speedy reply.

I updated to plotsr v0.5 and ran the tool again with `--rtr --reg IT97K:chr06:1-12000000`. The large inversion now shows, but I am still missing all the grey lines below the large inversion corresponding to the synteny among the last four genomes that you can see from the plot that includes all the chromosomes.

Here is the picture
[chr06aa.pdf](https://github.com/schneebergerlab/plotsr/files/8025947/chr06aa.pdf)

**Comment by mnshgl0110** [comment]
Hi Stefano,
I have updated selection of alignments when zooming in. On my simulated data it seems to be working better now.
![issue_7](https://user-images.githubusercontent.com/16225647/153231141-f2291fae-1f18-4639-b537-39ee500c4d9e.png)

Could you please try it with your read data?

You would need to download and install it through git using the following in your python environament:
```
git clone https://github.com/schneebergerlab/plotsr.git
cd plotsr
python setup.py install
```

**Comment by StefanoLonardi** [comment]
Hi Manesh, it worked! thanks so much.
[chr06-0Mto12M.pdf](https://github.com/schneebergerlab/plotsr/files/8036520/chr06-0Mto12M.pdf)
